'''Crie arquivo .py crie um programa que vai conter duas variáveis, nome_a com o valor 
"Python" e nome_b com o valor "python". Use o operador de igualdade para verificar se elas 
são iguais e exiba o resultado (True ou False) na tela, seguindo essa estrutura "nome_a é 
igual ao nome_b? operação_de_comparação".'''

nome_a = "Python"
nome_b = "python"
resultado = nome_a == nome_b
print(f"{nome_a} é igual ao {nome_b}? {resultado}")
