'''Crie um arquivo .py, crie um programa que vai conter duas variáveis, valor1 com o valor 
10.50 e valor2 com o valor 12.00. Use o operador de diferença [ != ] para verificar se elas 
são diferentes e exiba o resultado na tela seguindo essa estrutura "valor1 é igual ao valor2? 
operação_de_comparação".'''

valor1 = 10.50
valor2 = 12.00
resultado = valor1 != valor2
print(f"{valor1} é igual ao {valor2}? {resultado}")
