'''Crie um arquivo .py. Crie uma variável booleana esta_chovendo com o valor True. Use o 
operador lógico not para verificar a condição contrária, ou seja, se NÃO está chovendo. 
Armazene o resultado em uma variável nao_esta_chovendo e exiba-o na tela seguindo a 
seguinte estrutura a seguir: “esta_chovendo = valor“ e “nao_esta_chovendo = valor“. '''

esta_chovendo = True
nao_esta_chovendo = not esta_chovendo
print(f"esta_chovendo = {esta_chovendo}")
print(f"nao_esta_chovendo = {nao_esta_chovendo}")
