'''Crie um arquivo .py. Use um laço while para exibir os números de 1 a 10 na tela. Cada 
número deve estar em uma nova linha. 
Obs: Lembre-se de usar uma variável temporária para controlar as quantidades que o bloco 
de código vai ser repetido, evitando o loop infinito. 
  variavel_temporaria = 0 
 while variavel_temporaria <= 5: 
     # Os códigos de dentro do while, vão se repetir enquanto a variável temporária 
     # for menor ou igual a 5, quando a variavel temporaria chegar tiver o valor igual a 
     # 5 ou maior que 5 os código de dentro do while não vão ser mais repetidos'''

variavel_temporaria = 1
while variavel_temporaria <= 10:
    print(variavel_temporaria)
    variavel_temporaria += 1