'''Crie um arquivo .py. Escreva um código que receba dois números do usuário e guarde nas 
variáveis A e B. Em seguida, calcule a soma, a subtração, a multiplicação e divisão de A por 
B. Mostre na tela cada um dos resultados na tela. '''

a = float(input("Digite um número: "))
b = float(input("Digite outro número: "))

soma = a + b
subtracao = a - b
multiplicacao = a * b
divisao = a / b

print("Soma:", soma)
print("Subtração:", subtracao)
print("Multiplicação:", multiplicacao)
print("Divisão:", divisao)