'''Crie um arquivo .py. Escreva um código, crie uma variável chamada is_vazio com o 
valor True. Em seguida, utilize o operador lógico not para inverter essa condição, 
verificando se a variável não está vazia, e armazene o resultado em uma nova variável 
chamada is_preenchido. Por fim, exiba na tela as mensagens "is_vazio = valor" e 
"is_preenchido = valor", substituindo valor pelos conteúdos correspondentes das 
variáveis, utilizando a função print().

'''

is_vazio = True
is_preenchido = not is_vazio
print("is_vazio =", is_vazio)
print("is_preenchido =", is_preenchido)